project:
  type: website
  resources:
    - artifacts/
    - admin/

website:
  title: "LETÍCIA OLIVERA<br><small>psicóloga</small>"
  navbar:
    left:
      - href: index.html
        text: Home
      - about.qmd

format:
  html:
    theme:
      - quartz
      - brand
    css: styles.css
    toc: true
    body-attrs: "class=title-centered"
